version: '3.8'

services:
  app:
    container_name: giropops-senhas
    build: .
    image: italoalmeidaa/linuxtips-giropops-senhas:1.0
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:latest
    expose:
      - "6379"
